/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bTabtest;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;

import javafx.stage.Stage;
import javafx.scene.Scene;
import javafx.scene.Parent;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
       
        Parent root = FXMLLoader.load(getClass().getClassLoader().getResource("App.fxml"));
        Scene scene = new Scene(root);

        // FXMLLoader loader = new FXMLLoader(getClass().getClassLoader().getResource("App.fxml"));
        // Parent root = loader.load();

        primaryStage.setTitle("Hello, World!");
        primaryStage.setMaximized(true);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        launch(args);
    }
}
